export type CreateAdapter = 'react' | 'vue' | 'svelte';

export interface CreateTemplateContext {
  adapter: CreateAdapter;
  appName: string;
  packageName: string;
  nodeEngine: string;
  facetheoryTarball: string;
  appTheoryTarball: string;
  appTheoryCdkTarball: string;
  tableTheoryTarball: string;
  dependencyVersions: Readonly<Record<string, string>>;
}

export interface CreateTemplateFile {
  path: string;
  content: string;
}

const CLIENT_BOOTSTRAP_MODULE = '/assets/client.js';

function withFinalNewline(content: string): string {
  return content.endsWith('\n') ? content : `${content}\n`;
}

function renderJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function dependencyVersion(
  ctx: CreateTemplateContext,
  name: string,
  fallback: string,
): string {
  return ctx.dependencyVersions[name] ?? fallback;
}

function renderPackageJson(ctx: CreateTemplateContext): string {
  const dependencies: Record<string, string> = {
    '@theory-cloud/apptheory': ctx.appTheoryTarball,
    '@theory-cloud/apptheory-cdk': ctx.appTheoryCdkTarball,
    '@theory-cloud/facetheory': ctx.facetheoryTarball,
    '@theory-cloud/tabletheory-ts': ctx.tableTheoryTarball,
  };

  if (ctx.adapter === 'react') {
    dependencies.react = dependencyVersion(ctx, 'react', '^19');
    dependencies['react-dom'] = dependencyVersion(ctx, 'react-dom', '^19');
  } else if (ctx.adapter === 'vue') {
    dependencies.vue = dependencyVersion(ctx, 'vue', '^3');
    dependencies['@vue/server-renderer'] = dependencyVersion(
      ctx,
      '@vue/server-renderer',
      '^3',
    );
  } else {
    dependencies.svelte = dependencyVersion(ctx, 'svelte', '^5.55.7');
  }

  const devDependencies: Record<string, string> = {
    '@types/node': dependencyVersion(ctx, '@types/node', '^24'),
    'aws-cdk-lib': dependencyVersion(ctx, 'aws-cdk-lib', '2.257.0'),
    constructs: dependencyVersion(ctx, 'constructs', '10.6.0'),
    esbuild: dependencyVersion(ctx, 'esbuild', '^0.28.1'),
    tsx: dependencyVersion(ctx, 'tsx', '^4.22.3'),
    typescript: dependencyVersion(ctx, 'typescript', '^5.9.3'),
    vite: dependencyVersion(ctx, 'vite', '^8'),
  };

  if (ctx.adapter === 'react') {
    devDependencies['@types/react'] = dependencyVersion(
      ctx,
      '@types/react',
      '^19',
    );
    devDependencies['@types/react-dom'] = dependencyVersion(
      ctx,
      '@types/react-dom',
      '^19',
    );
  } else if (ctx.adapter === 'svelte') {
    devDependencies['@sveltejs/vite-plugin-svelte'] = dependencyVersion(
      ctx,
      '@sveltejs/vite-plugin-svelte',
      '^7',
    );
  }

  return renderJson({
    name: ctx.packageName,
    version: '0.1.0',
    private: true,
    type: 'module',
    engines: {
      node: ctx.nodeEngine,
    },
    scripts: {
      'build:client': 'vite build --config vite.config.ts',
      'cdk:synth': 'tsx infra/app.ts',
      typecheck: 'tsc -p tsconfig.json --noEmit',
      check: 'npm run typecheck',
      build: 'npm run build:client && npm run typecheck',
    },
    dependencies,
    devDependencies,
    overrides: {
      '@theory-cloud/apptheory': {
        '@theory-cloud/tabletheory-ts': ctx.tableTheoryTarball,
      },
    },
  });
}

function renderTsconfig(ctx: CreateTemplateContext): string {
  return renderJson({
    compilerOptions: {
      target: 'ES2022',
      module: 'NodeNext',
      moduleResolution: 'NodeNext',
      strict: true,
      forceConsistentCasingInFileNames: true,
      skipLibCheck: true,
      resolveJsonModule: true,
      ...(ctx.adapter === 'react' ? { jsx: 'react-jsx' } : {}),
      types: ['node'],
    },
    include: ['src', 'infra', 'vite.config.ts'],
  });
}

function renderReadme(ctx: CreateTemplateContext): string {
  return withFinalNewline(`# ${ctx.appName}

Generated by \`facetheory create --adapter ${ctx.adapter}\`.

## Install

This starter stays pinned to the immutable FaceTheory GitHub Release tarball that generated it:

\`\`\`bash
npm install --save-exact \\
  "${ctx.facetheoryTarball}"

npm install
\`\`\`

The generated \`package.json\` also pins AppTheory, AppTheory CDK, and TableTheory through GitHub Release tarballs and keeps the npm \`overrides\` block aligned so AppTheory resolves the same TableTheory runtime.

## Develop locally

\`\`\`bash
npm run check
npm run build:client
\`\`\`

The server Face uses \`${CLIENT_BOOTSTRAP_MODULE}\` as its hydration bootstrap module. The Vite build emits that deterministic client entry into \`dist/client\`, and the CDK stack deploys that directory under the AppTheorySsrSite \`assets\` prefix.

## AWS deployment shape

\`infra/stack.ts\` is an \`AppTheorySsrSite\`-based CDK stack. It creates an S3 assets bucket, bundles \`src/handler.ts\` as the SSR Lambda, and routes CloudFront to the Lambda Function URL through AppTheory's OAC/IAM path.

Do not deploy from the starter until an operator has reviewed the account, domain, retention, WAF, and removal-policy settings for your environment.
`);
}

function renderViteConfig(ctx: CreateTemplateContext): string {
  const entry = ctx.adapter === 'react' ? 'src/client.tsx' : 'src/client.ts';
  const pluginImport =
    ctx.adapter === 'svelte'
      ? "import { svelte } from '@sveltejs/vite-plugin-svelte';\n"
      : '';
  const plugins = ctx.adapter === 'svelte' ? '  plugins: [svelte()],\n' : '';

  return withFinalNewline(`${pluginImport}import { defineConfig } from 'vite';

export default defineConfig({
${plugins}  build: {
    manifest: true,
    outDir: 'dist/client',
    emptyOutDir: true,
    rollupOptions: {
      input: '${entry}',
      output: {
        entryFileNames: 'client.js',
        chunkFileNames: 'chunks/[name]-[hash].js',
        assetFileNames: 'assets/[name]-[hash][extname]',
      },
    },
  },
});
`);
}

function renderHandler(): string {
  return withFinalNewline(`import {
  createApp,
  createLambdaFunctionURLStreamingHandler,
} from '@theory-cloud/apptheory';
import { createAppTheoryFaceHandler } from '@theory-cloud/facetheory/apptheory';

import { app as faceApp } from './face-app.js';

const runtime = createApp();
const faceHandler = createAppTheoryFaceHandler({ app: faceApp });

runtime.get('/', faceHandler);
runtime.get('/{proxy+}', faceHandler);
runtime.handle('HEAD', '/', faceHandler);
runtime.handle('HEAD', '/{proxy+}', faceHandler);

export const handler = createLambdaFunctionURLStreamingHandler(runtime);
`);
}

function renderInfraApp(): string {
  return withFinalNewline(`import { App } from 'aws-cdk-lib';

import { FaceTheoryStarterStack } from './stack.js';

const app = new App();

new FaceTheoryStarterStack(app, 'FaceTheoryStarter');
`);
}

function renderInfraStack(): string {
  return withFinalNewline(`import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { CfnOutput, Duration, RemovalPolicy, Stack, type StackProps } from 'aws-cdk-lib';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import { AppTheorySsrSite } from '@theory-cloud/apptheory-cdk';
import { Construct } from 'constructs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(__dirname, '..');

export class FaceTheoryStarterStack extends Stack {
  public readonly site: AppTheorySsrSite;

  constructor(scope: Construct, id: string, props: StackProps = {}) {
    super(scope, id, props);

    const assetsBucket = new s3.Bucket(this, 'AssetsBucket', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      removalPolicy: RemovalPolicy.RETAIN,
    });

    const ssrFunction = new NodejsFunction(this, 'SsrFunction', {
      runtime: lambda.Runtime.NODEJS_20_X,
      entry: path.resolve(projectRoot, 'src/handler.ts'),
      handler: 'handler',
      timeout: Duration.seconds(10),
      memorySize: 512,
      bundling: {
        minify: false,
        sourceMap: false,
      },
    });

    new s3deploy.BucketDeployment(this, 'ClientAssetsDeployment', {
      sources: [s3deploy.Source.asset(path.resolve(projectRoot, 'dist/client'))],
      destinationBucket: assetsBucket,
      destinationKeyPrefix: 'assets',
      prune: true,
      cacheControl: [s3deploy.CacheControl.fromString('public,max-age=31536000,immutable')],
    });

    this.site = new AppTheorySsrSite(this, 'Site', {
      ssrFunction,
      ssrUrlAuthType: lambda.FunctionUrlAuthType.AWS_IAM,
      assetsBucket,
      assetsKeyPrefix: 'assets',
      assetsManifestKey: '.vite/manifest.json',
      directS3PathPatterns: ['/.vite/*'],
      enableLogging: true,
    });

    new CfnOutput(this, 'CloudFrontDomainName', {
      value: this.site.distribution.distributionDomainName,
    });
  }
}
`);
}

function renderReactFiles(): CreateTemplateFile[] {
  return [
    {
      path: 'src/types.ts',
      content: withFinalNewline(`export type HomeData = {
  message: string;
};
`),
    },
    {
      path: 'src/app.tsx',
      content: withFinalNewline(`import type { HomeData } from './types.js';

export function App({ message }: HomeData) {
  return (
    <main>
      <h1>FaceTheory React starter</h1>
      <p>{message}</p>
    </main>
  );
}
`),
    },
    {
      path: 'src/face-app.tsx',
      content: withFinalNewline(`import { createFaceApp } from '@theory-cloud/facetheory';
import { createReactFace } from '@theory-cloud/facetheory/react';

import { App } from './app.js';
import type { HomeData } from './types.js';

const CLIENT_BOOTSTRAP_MODULE = '${CLIENT_BOOTSTRAP_MODULE}';

export const app = createFaceApp({
  faces: [
    createReactFace<HomeData>({
      route: '/',
      mode: 'ssr',
      load: async () => ({ message: 'Hello from a FaceTheory React Face.' }),
      render: (_ctx, data) => (
        <div id="root">
          <App message={data.message} />
        </div>
      ),
      renderOptions: (_ctx, data) => ({
        headTags: [
          { type: 'title', text: 'FaceTheory React starter' },
          { type: 'meta', attrs: { name: 'viewport', content: 'width=device-width,initial-scale=1' } },
        ],
        hydration: {
          data,
          bootstrapModule: CLIENT_BOOTSTRAP_MODULE,
        },
      }),
    }),
  ],
});
`),
    },
    {
      path: 'src/client.tsx',
      content: withFinalNewline(`import { loadFaceHydrationData } from '@theory-cloud/facetheory/client';
import { hydrateRoot } from 'react-dom/client';

import { App } from './app.js';
import type { HomeData } from './types.js';

const data = (await loadFaceHydrationData<HomeData>()) ?? {
  message: 'Hello from the client fallback.',
};
const root = document.getElementById('root');

if (!root) {
  throw new Error('FaceTheory React starter could not find #root to hydrate');
}

hydrateRoot(root, <App message={data.message} />);
`),
    },
  ];
}

function renderVueFiles(): CreateTemplateFile[] {
  return [
    {
      path: 'src/types.ts',
      content: withFinalNewline(`export type HomeData = {
  message: string;
};
`),
    },
    {
      path: 'src/app.ts',
      content: withFinalNewline(`import { defineComponent, h } from 'vue';

export const App = defineComponent({
  name: 'FaceTheoryStarterApp',
  props: {
    message: {
      type: String,
      required: true,
    },
  },
  setup(props) {
    return () =>
      h('main', [
        h('h1', 'FaceTheory Vue starter'),
        h('p', props.message),
      ]);
  },
});
`),
    },
    {
      path: 'src/face-app.ts',
      content: withFinalNewline(`import { createFaceApp } from '@theory-cloud/facetheory';
import { createVueFace, h } from '@theory-cloud/facetheory/vue';

import { App } from './app.js';
import type { HomeData } from './types.js';

const CLIENT_BOOTSTRAP_MODULE = '${CLIENT_BOOTSTRAP_MODULE}';

export const app = createFaceApp({
  faces: [
    createVueFace<HomeData>({
      route: '/',
      mode: 'ssr',
      load: async () => ({ message: 'Hello from a FaceTheory Vue Face.' }),
      render: (_ctx, data) =>
        h('div', { id: 'root' }, [h(App, { message: data.message })]),
      renderOptions: (_ctx, data) => ({
        headTags: [
          { type: 'title', text: 'FaceTheory Vue starter' },
          { type: 'meta', attrs: { name: 'viewport', content: 'width=device-width,initial-scale=1' } },
        ],
        hydration: {
          data,
          bootstrapModule: CLIENT_BOOTSTRAP_MODULE,
        },
      }),
    }),
  ],
});
`),
    },
    {
      path: 'src/client.ts',
      content: withFinalNewline(`import { loadFaceHydrationData } from '@theory-cloud/facetheory/client';
import { createSSRApp, h } from 'vue';

import { App } from './app.js';
import type { HomeData } from './types.js';

const data = (await loadFaceHydrationData<HomeData>()) ?? {
  message: 'Hello from the client fallback.',
};
const root = document.getElementById('root');

if (!root) {
  throw new Error('FaceTheory Vue starter could not find #root to hydrate');
}

createSSRApp({
  render: () => h(App, { message: data.message }),
}).mount(root);
`),
    },
  ];
}

function renderSvelteFiles(): CreateTemplateFile[] {
  return [
    {
      path: 'src/types.ts',
      content: withFinalNewline(`export type HomeData = {
  message: string;
};
`),
    },
    {
      path: 'src/svelte.d.ts',
      content: withFinalNewline(`declare module '*.svelte' {
  import type { Component } from 'svelte';

  const component: Component<Record<string, unknown>>;
  export default component;
}
`),
    },
    {
      path: 'src/App.svelte',
      content: withFinalNewline(`<script lang="ts">
  let { message }: { message: string } = $props();
</script>

<main>
  <h1>FaceTheory Svelte starter</h1>
  <p>{message}</p>
</main>
`),
    },
    {
      path: 'src/face-app.ts',
      content: withFinalNewline(`import { createFaceApp } from '@theory-cloud/facetheory';
import { createSvelteFace } from '@theory-cloud/facetheory/svelte';

import App from './App.svelte';
import type { HomeData } from './types.js';

const CLIENT_BOOTSTRAP_MODULE = '${CLIENT_BOOTSTRAP_MODULE}';

export const app = createFaceApp({
  faces: [
    createSvelteFace<HomeData, HomeData>({
      route: '/',
      mode: 'ssr',
      load: async () => ({ message: 'Hello from a FaceTheory Svelte Face.' }),
      render: (_ctx, data) => ({
        component: App,
        props: { message: data.message },
      }),
      renderOptions: (_ctx, data) => ({
        headTags: [
          { type: 'title', text: 'FaceTheory Svelte starter' },
          { type: 'meta', attrs: { name: 'viewport', content: 'width=device-width,initial-scale=1' } },
        ],
        hydration: {
          data,
          bootstrapModule: CLIENT_BOOTSTRAP_MODULE,
        },
      }),
    }),
  ],
});
`),
    },
    {
      path: 'src/client.ts',
      content: withFinalNewline(`import { loadFaceHydrationData } from '@theory-cloud/facetheory/client';
import { hydrate } from 'svelte';

import App from './App.svelte';
import type { HomeData } from './types.js';

const data = (await loadFaceHydrationData<HomeData>()) ?? {
  message: 'Hello from the client fallback.',
};
const root = document.getElementById('root');

if (!root) {
  throw new Error('FaceTheory Svelte starter could not find #root to hydrate');
}

hydrate(App, {
  target: root,
  props: { message: data.message },
});
`),
    },
  ];
}

export function renderCreateTemplate(ctx: CreateTemplateContext): CreateTemplateFile[] {
  const adapterFiles =
    ctx.adapter === 'react'
      ? renderReactFiles()
      : ctx.adapter === 'vue'
        ? renderVueFiles()
        : renderSvelteFiles();

  return [
    { path: 'package.json', content: renderPackageJson(ctx) },
    { path: 'tsconfig.json', content: renderTsconfig(ctx) },
    { path: 'README.md', content: renderReadme(ctx) },
    { path: 'vite.config.ts', content: renderViteConfig(ctx) },
    { path: 'src/handler.ts', content: renderHandler() },
    { path: 'infra/app.ts', content: renderInfraApp() },
    { path: 'infra/stack.ts', content: renderInfraStack() },
    ...adapterFiles,
  ];
}
